### ISSUE TITLE
Icon are too small in waybar

### ISSUE THREAD

**Issue by neolectron** [neolectron/dotfiles#1]
There's an issue where Icons in waybar are super small, I don't know if it's related to the default font used (fontawesome) or not.

I tried to zoom them in the waybar `styles.css` but it also increase the size of the bar itself, and just doesn't work. I think I need to find a font with icons properly sized in order to make it work.

![image](https://user-images.githubusercontent.com/5268400/210215717-df6fe4fb-073c-40f3-8a18-7f4b1b97e9e0.png)

**Comment by neolectron** [comment]
fixed

**Comment by Incognitux** [comment]
I am facing this same issue with my config, can I know how you fixed it for yourself?

**Comment by Incognitux** [comment]
so i fixed it by adding the icon font to font-family in style.css
```
* {
  font-family: "AestheticIosevka Nerd Font Mono", "Material Design Icons Desktop";
  font-size: 15px;
}
```

**Comment by neolectron** [comment]
Thank you, I think I also fixed it by changing the icon-font I'm using.

Ideally I'm thinking if icon could be derived from the app native icon that would be sick.

A little more like windows in the end, the chrome icon for my internet workspace could be derived from the app, it would also fix the issue when an app is not really in the list, no more "default square icon" thingy.

But I'm not yet sure how to do that, I'll keep it for the next iteration.
